const navList = [
  {
    name: '首页',
    id: 'firstPage',
    icon: '',
    isEnable: true,
    isShowIcon: false,
    isSeen: true,
  },
  {
    name: '电影',
    id: 'moive',
    icon: '',
    isEnable: true,
    isShowIcon: false,
    isSeen: true,
  },
  {
    name: '电视剧',
    id: 'teleplay',
    icon: '',
    isEnable: true,
    isShowIcon: false,
    isSeen: true,
  },
  {
    name: '综艺',
    id: 'varietyArts',
    icon: '',
    isEnable: true,
    isShowIcon: false,
    isSeen: true,
  },
  {
    name: '动漫',
    id: 'animation',
    icon: '',
    isEnable: true,
    isShowIcon: false,
    isSeen: true,
  },
  {
    name: '排行榜',
    id: 'rankList',
    icon: '',
    isEnable: true,
    isShowIcon: false,
    isSeen: true,
  },
  {
    name: '最近更新',
    id: 'latestUpdate',
    icon: '',
    isEnable: true,
    isShowIcon: false,
    isSeen: true,
  },
  {
    name: '导航',
    id: 'navigate',
    icon: '',
    isEnable: true,
    isShowIcon: false,
    isSeen: true,
  },
]

export { navList }
